### ISSUE TITLE
Saying hi

### ISSUE THREAD

**Issue by dac09** [Codepath-MSU-iOS-Project/CP_Project#16]
Hi @mars0202, this isn't an issue, but didn't have a way of contacting you apart from this.

I noticed on the gifox issues that you wanted an easy way of recording your simulator screens without a frame and shadow. If you're interested I've been working on a cli tool that could solve your problem (looks like it would be helpful for you on this repo). 

Links:
Product Website: https://www.tape.sh/
Opensource CLI: https://github.com/edamameldn/tape-cli

Let me know if it works for you!

**Comment by mars0202** [comment]
Hey! No worries for reaching out this way. This looks great! I will def check it out. Thank you!
